-- Generated by hyprconf2lua v1.4.0, manually corrected
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Fixed: $mod/$mod2/$bin were defined in the parent binds.conf under classic
-- hyprlang (flat textual inclusion) but don't carry into this file's Lua
-- module scope (require() is scoped) -- so this file needs its own locals.

---@module 'hl'

-- Lines ending with `# [hidden]` won't be shown on cheatsheet
-- Lines starting with #! are section headings

-- Configuration Variables
local mod = "ALT"
local mod2 = "SUPER"
local bin = os.getenv("HOME") .. "/.local/bin"
local term = "kitty"
local browser = "zen-browser"
local chrome = "chromium --new-window"
local qs = "qs -c sleex"
local ipc = "qs -c sleex ipc call"

-- $mod2_L / $mod_L were never defined anywhere in this config tree (checked
-- env.conf, start.conf, binds.conf, windowrules.conf, animations.conf) --
-- resolved to Hyprland's documented physical-modifier-key names (SUPER_L /
-- ALT_L), matching the naming convention and the well-known "tap modifier
-- to open launcher" idiom -- see
-- https://wiki.hypr.land/Configuring/Basics/Binds/#catch-all
local mod2_L = "SUPER_L"
local mod_L = "ALT_L"

--! Shell keybinds
--#! Launcher

hl.bind(mod2 .. " + " .. mod2_L, hl.dsp.global("quickshell:overviewToggleRelease"), { ignore_mods = true })
-- Toggle overview/launcher
hl.bind(mod2 .. " + " .. mod2_L, hl.dsp.exec_cmd("qs -c sleex ipc call TEST_ALIVE || pkill fuzzel || fuzzel"))
-- [hidden] Launcher (fallback)
hl.bind("catchall", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"), { ignore_mods = true, transparent = true, non_consuming = true })
-- [hidden]
hl.bind("CTRL" .. " + " .. mod2_L, hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:272", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:273", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:274", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:275", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:276", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse:277", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse_up", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2 .. " + " .. "mouse_down", hl.dsp.global("quickshell:overviewToggleReleaseInterrupt"))
-- [hidden]
hl.bind(mod2_L, hl.dsp.global("quickshell:workspaceNumber"), { ignore_mods = true, transparent = true })
-- [hidden]
hl.bind(mod_L, hl.dsp.global("quickshell:workspaceNumber"), { ignore_mods = true, transparent = true })
-- [hidden]

--#! Features

hl.bind(mod2 .. " + " .. "V", hl.dsp.global("quickshell:overviewClipboardToggle"))
hl.bind(mod2 .. " + " .. "Period", hl.dsp.global("quickshell:overviewEmojiToggle"))
hl.bind(mod2 .. " + " .. "A", hl.dsp.global("quickshell:sidebarLeftToggle"))
hl.bind(mod .. " + " .. mod2 .. " + " .. "A", hl.dsp.global("quickshell:sidebarLeftToggleDetach"))
hl.bind(mod2 .. " + " .. "D", hl.dsp.global("quickshell:dashboardToggle"))
hl.bind(mod2 .. " + " .. "Slash", hl.dsp.global("quickshell:cheatsheetToggle"))
hl.bind(mod2 .. " + " .. "M", hl.dsp.global("quickshell:mediaControlsToggle"))
hl.bind(mod .. " + CTRL" .. " + " .. "Delete", hl.dsp.global("quickshell:sessionToggle"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "s", hl.dsp.global("quickshell:sessionToggle"))
hl.bind(mod2 .. " + " .. "J", hl.dsp.global("quickshell:barToggle"))

--#! Session

hl.bind(mod2 .. " + " .. "l", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mod2 .. " + CTRL" .. " + " .. "l", hl.dsp.exec_cmd("loginctl lock-session"))
-- [hidden]
hl.bind(mod2 .. " + CTRL" .. " + " .. "l", hl.dsp.exec_cmd("sleep 0.1 && systemctl suspend || loginctl suspend"), { locked = true })
hl.bind(mod .. " + " .. mod2 .. " + CTRL + SHIFT" .. " + " .. "Delete", hl.dsp.exec_cmd("systemctl poweroff || loginctl poweroff"))

--#! Misc

hl.bind(mod2 .. " + CTRL + ALT" .. " + " .. "R", hl.dsp.exec_cmd("qs -c sleex kill; qs -c sleex -d"), { repeating = true })
hl.bind(mod2 .. " + CTRL + ALT" .. " + " .. "K", hl.dsp.exec_cmd("qs -c sleex kill"), { repeating = true })
hl.bind(mod2 .. " + " .. "L", hl.dsp.global("loginctl lock-session"))

--## Restore lock

hl.bind(mod .. " + " .. mod2 .. " + " .. "L", hl.dsp.exec_cmd("qs -c sleex"), { locked = true })
hl.bind(mod .. " + " .. mod2 .. " + " .. "L", hl.dsp.global("loginctl lock-session"), { locked = true })

--! Applications
--#! General

hl.bind(mod .. " + SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd(term))
hl.bind(mod2 .. " + " .. "b", hl.dsp.exec_cmd(browser))
hl.bind(mod2 .. " + " .. "e", hl.dsp.exec_cmd("spacedrive"))

-- ## Pyrpland
-- bind = $mod SHIFT, s, exec, pypr toggle ncmpcpp
-- bind = $mod SHIFT, t, exec, pypr toggle term

--#! Misc

hl.bind(mod .. " + SHIFT" .. " + " .. "s", hl.dsp.exec_cmd("pkill ncmpcpp || kitty -1 ncmpcpp"))
hl.bind("CTRL + SHIFT" .. " + " .. "Escape", hl.dsp.exec_cmd("kitty -1 btop"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "v", hl.dsp.exec_cmd(bin .. "/vigiland -t"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "c", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(mod2 .. " + " .. "F1", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/gamemode.sh"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "Minus", hl.dsp.exec_cmd(bin .. "/zoom.sh decrease 0.1"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "Equal", hl.dsp.exec_cmd(bin .. "/zoom.sh increase 0.1"))
hl.bind(mod .. " + CTRL" .. " + " .. "f", hl.dsp.window.resize({ x = 1200, y = 680 }))

--#! Productivity

hl.bind(mod2 .. " + SHIFT" .. " + " .. "e", hl.dsp.exec_cmd("kitty -1 nvim"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "d", hl.dsp.exec_cmd("code"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "y", hl.dsp.exec_cmd("youtube-music"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "a", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.apps/Capacities-*.AppImage"))
-- bindd = $mod2 SHIFT, t, Opens Todoist, exec, $bin/todo
hl.bind(mod2 .. " + SHIFT" .. " + " .. "t", hl.dsp.exec_cmd(bin .. "/ticktick"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "n", hl.dsp.exec_cmd("notion-app"))
hl.bind(mod2 .. " + CTRL + SHIFT" .. " + " .. "n", hl.dsp.exec_cmd(bin .. "/obsidian"))
-- bindd = $mod2 SHIFT, t, Opens Tana, exec, $chrome --app=https://app.tana.inc
-- bindd = $mod2 SHIFT, b, Opens Cashew Budgetting, exec, $chrome --app=https://budget-track.web.app/
hl.bind(mod2 .. " + SHIFT" .. " + " .. "m", hl.dsp.exec_cmd(chrome .. " --app=https://messages.google.com/web/conversations"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. 0, hl.dsp.exec_cmd(chrome .. " --app=https://robinhood.com/legend"))
hl.bind(mod2 .. " + CTRL" .. " + " .. "d", hl.dsp.exec_cmd("discord"))
-- bindd = $mod2 CTRL, p, Opens Proxmox Server, exec, $browser -new-window "https://192.168.1.211:8006"

-- ##! Fuzzel
-- bindd = $mod2, v, Clipboard history, exec, pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy
-- bindd = $mod2, Period, Emoji picker menu, exec, pkill fuzzel || $bin/fuzzel-emoji.sh

--# -- Notifications -- ##
-- bind = $mod, n, exec, swaync-client -t -sw # Toggle Window
-- bind = $mod CTRL, n, exec, swaync-client -d # Do not Disturb
-- bind = $mod SHIFT, n, exec, swaync-client -C # Close all
-- bind = $mod CTRL SHIFT, n, exec, killall swaync && swaync & # swaync-client -R -rs # Reload

--! Screen
--#! Screenshot

hl.bind("Print", hl.dsp.exec_cmd(bin .. "/scr monitor"))
hl.bind("CTRL + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr area"))
hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr area-annotate"))
hl.bind(mod .. " + CTRL" .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr area-annotate-delay"))
hl.bind(mod .. " + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr extract"))

--#! Screen Record

hl.bind(mod2 .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr screenrec"))
hl.bind(mod2 .. " + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(bin .. "/scr screenrec-audio"))

--#! AI

hl.bind(mod .. " + " .. mod2 .. " + SHIFT" .. " + " .. "mouse:273", hl.dsp.exec_cmd(bin .. "/primary-buffer-query.sh"))

--#! Screen modification

hl.bind(mod2 .. " + SHIFT" .. " + " .. "l", hl.dsp.exec_cmd(bin .. "/sunset"))
-- Night time screen mode
hl.bind(mod2 .. " + SHIFT" .. " + " .. "p", hl.dsp.exec_cmd("hyprctl dispatch dpms toggle"), { locked = true })
-- Toggle on/off screen
hl.bind(mod2 .. " + SHIFT + CTRL" .. " + " .. "p", hl.dsp.exec_cmd("hyprctl dispatch dpms off"), { locked = true })
-- Screen off
hl.bind(mod2 .. " + CTRL" .. " + " .. "p", hl.dsp.exec_cmd("hyprctl dispatch dpms on"), { locked = true })
-- Screen on

--! Media
--#! Local Media

hl.bind("CTRL" .. " + " .. "XF86AudioNext", hl.dsp.exec_cmd("mpc next"), { locked = true })
hl.bind("CTRL" .. " + " .. "XF86AudioPrev", hl.dsp.exec_cmd("mpc prev"), { locked = true })
hl.bind("CTRL" .. " + " .. "XF86AudioPlay", hl.dsp.exec_cmd("mpc toggle"), { locked = true })
hl.bind("CTRL" .. " + " .. "XF86AudioStop", hl.dsp.exec_cmd("mpc stop"), { locked = true })

--#! Streaming Media

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })
hl.bind(mod2 .. " + " .. "Space", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(mod2 .. " + " .. "Equal", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind(mod2 .. " + " .. "Minus", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#! Volume Control

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pulsemixer --change-volume +2"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pulsemixer --change-volume -2"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pulsemixer --toggle-mute"), { locked = true })
hl.bind("CTRL" .. " + " .. "XF86AudioMute", hl.dsp.exec_cmd("pulsemixer --toggle-mute --id source-64"), { locked = true })

--#! Brightness Control

hl.bind("CTRL" .. " + " .. "XF86AudioRaiseVolume", hl.dsp.global("quickshell:brightnessIncrease"), { locked = true })
hl.bind("CTRL" .. " + " .. "XF86AudioLowerVolume", hl.dsp.global("quickshell:brightnessDecrease"), { locked = true })
