-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --== Shadorain Hyprland Keybinds ==-- #

-- Configuration Variables

local mod = "ALT"

local mod2 = "SUPER"

local bin = os.getenv("HOME") .. "/.local/bin" -- Local binary path
local hs = require("hyprsplit")



-- DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND

hl.define_submap("global", function()
    -- This is required for catchall to work
    require("config.app_binds")

    -- Workspaces
    hl.bind(mod .. " + " .. "CTRL + SHIFT" .. " + " .. "s", hl.dsp.window.move({ workspace = "special" }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "s", hl.dsp.workspace.toggle_special(nil))
    --# [hyprsplit]
    --## Focus
    hl.bind(mod .. " + " .. "1", hs.dsp.focus({ workspace = 1 }))
    hl.bind(mod .. " + " .. "2", hs.dsp.focus({ workspace = 2 }))
    hl.bind(mod .. " + " .. "3", hs.dsp.focus({ workspace = 3 }))
    hl.bind(mod .. " + " .. "4", hs.dsp.focus({ workspace = 4 }))
    hl.bind(mod .. " + " .. "5", hs.dsp.focus({ workspace = 5 }))
    hl.bind(mod .. " + " .. "6", hs.dsp.focus({ workspace = 6 }))
    hl.bind(mod .. " + " .. "7", hs.dsp.focus({ workspace = 7 }))
    hl.bind(mod .. " + " .. "8", hs.dsp.focus({ workspace = 8 }))
    hl.bind(mod .. " + " .. "9", hs.dsp.focus({ workspace = 9 }))
    --## Move
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "1", hs.dsp.window.move({ workspace = 1, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "2", hs.dsp.window.move({ workspace = 2, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "3", hs.dsp.window.move({ workspace = 3, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "4", hs.dsp.window.move({ workspace = 4, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "5", hs.dsp.window.move({ workspace = 5, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "6", hs.dsp.window.move({ workspace = 6, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "7", hs.dsp.window.move({ workspace = 7, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "8", hs.dsp.window.move({ workspace = 8, follow = false }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "9", hs.dsp.window.move({ workspace = 9, follow = false }))
    hl.bind(mod .. " + " .. mod2 .. " + " .. "1", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/pull-workspaces-to-current"))
    --## Swaps
    hl.bind(mod .. " + " .. "g", hs.dsp.grab_rogue_windows())
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "w", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "1" }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "e", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "0" }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "r", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "2" }))
    -- Monitors
    hl.bind(mod .. " + " .. "w", hl.dsp.focus({ monitor = 1 }))
    hl.bind(mod .. " + " .. "e", hl.dsp.focus({ monitor = 0 }))
    hl.bind(mod .. " + " .. "r", hl.dsp.focus({ monitor = 2 }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "w", hl.dsp.window.move({ monitor = 1 }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "e", hl.dsp.window.move({ monitor = 0 }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "r", hl.dsp.window.move({ monitor = 2 }))
    -- Management
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "c", hl.dsp.window.close())
    hl.bind(mod .. " + " .. "CTRL + SHIFT" .. " + " .. "c", hl.dsp.exec_cmd("hyprctl kill"))
    -- Forcefully zap a window
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "Q", hl.dsp.exit())
    hl.bind(mod .. " + " .. "t", hl.dsp.window.float())
    hl.bind(mod .. " + " .. "f", hl.dsp.window.fullscreen({ mode = "maximized" }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "f", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
    -- Maximize
    hl.bind(mod .. " + " .. mod2 .. " + " .. "f", hl.dsp.window.fullscreen_state({ internal = 0, client = 3 }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "p", hl.dsp.window.pin())
    --# Minimize -- doesnt seem to ever come back
    -- bind = $mod, z, togglespecialworkspace, min
    -- bind = $mod, z, movetoworkspace, +0
    -- bind = $mod, z, togglespecialworkspace, min
    -- bind = $mod, z, movetoworkspace, special:min
    -- bind = $mod, z, togglespecialworkspace, min
    -- bind = $mod, x, togglespecialworkspace, min2
    -- bind = $mod, x, movetoworkspace, +0
    -- bind = $mod, x, togglespecialworkspace, min2
    -- bind = $mod, x, movetoworkspace, special:min2
    -- bind = $mod, x, togglespecialworkspace, min2
    -- Layout
    --# Master
    hl.bind(mod .. " + " .. "Return", hl.dsp.layout("swapwithmaster"))
    --# Dwindle
    -- bind = $mod SHIFT, x, togglegroup, none
    -- bind = $mod CTRL, x, togglesplit,
    -- bind = $mod CTRL SHIFT, x, changegroupactive, f
    -- Window
    hl.bind(mod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))
    hl.bind(mod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))
    hl.bind(mod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))
    hl.bind(mod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))
    --# Move
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.move({ direction = "l" }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.move({ direction = "r" }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.move({ direction = "u" }))
    hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.move({ direction = "d" }))
    --# Resize
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
    hl.bind(mod .. " + " .. "CTRL" .. " + " .. "j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))
    -- Mouse
    hl.bind(mod2 .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
    hl.bind(mod2 .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
    hl.bind(mod2 .. " + " .. "mouse_down", hs.dsp.focus({ workspace = "e+1" }))
    hl.bind(mod2 .. " + " .. "mouse_up", hs.dsp.focus({ workspace = "e-1" }))
    -- Plugins
    -- # Toggle all keybinds
    -- # WARNING: (Needs to be at the bottom or keybinds under it wont work)
    -- bind = $mod SHIFT, z, submap, clean
    -- submap = clean
    -- bind = $mod SHIFT, z, submap, reset
    -- submap = reset
end)


-- Exec (run on initial startup AND every reload, matching the old `exec =`
-- semantics -- config.reloaded alone does NOT fire on the first launch).
-- Dispatch directly in Lua rather than shelling out to `hyprctl dispatch`,
-- whose CLI now expects a single Lua expression string, not the old
-- space-separated `<dispatcher> <arg>` form.
hl.on("hyprland.start", function()
    hl.dispatch(hl.dsp.submap("global"))
end)
hl.on("config.reloaded", function()
    hl.dispatch(hl.dsp.submap("global"))
end)
