# --== Shadorain Hyprland Keybinds ==-- #

# Configuration Variables
$mod = Alt
$mod2 = Super
$bin = $HOME/.local/bin # Local binary path

exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

source = ~/.config/hypr/config/app_binds.conf

# Workspaces
bind = $mod Ctrl Shift, s, movetoworkspace, special
bind = $mod Ctrl, s, togglespecialworkspace,
## [hyprsplit]
### Focus
bind = $mod, 1, split:workspace, 1
bind = $mod, 2, split:workspace, 2
bind = $mod, 3, split:workspace, 3
bind = $mod, 4, split:workspace, 4
bind = $mod, 5, split:workspace, 5
bind = $mod, 6, split:workspace, 6
bind = $mod, 7, split:workspace, 7
bind = $mod, 8, split:workspace, 8
bind = $mod, 9, split:workspace, 9
### Move
bind = $mod Shift, 1, split:movetoworkspacesilent, 1
bind = $mod Shift, 2, split:movetoworkspacesilent, 2
bind = $mod Shift, 3, split:movetoworkspacesilent, 3
bind = $mod Shift, 4, split:movetoworkspacesilent, 4
bind = $mod Shift, 5, split:movetoworkspacesilent, 5
bind = $mod Shift, 6, split:movetoworkspacesilent, 6
bind = $mod Shift, 7, split:movetoworkspacesilent, 7
bind = $mod Shift, 8, split:movetoworkspacesilent, 8
bind = $mod Shift, 9, split:movetoworkspacesilent, 9
bind = $mod Ctrl Shift, 1, exec, $bin/pull-windows-to-workspace-1
### Swaps
bind = $mod, g, split:grabroguewindows
bind = $mod Ctrl, w, split:swapactiveworkspaces, current 1
bind = $mod Ctrl, e, split:swapactiveworkspaces, current 0
bind = $mod Ctrl, r, split:swapactiveworkspaces, current 2

# Monitors
bind = $mod, w, focusmonitor, 1
bind = $mod, e, focusmonitor, 0
bind = $mod, r, focusmonitor, 2
bind = $mod Shift, w, movewindow, mon:1
bind = $mod Shift, e, movewindow, mon:0
bind = $mod Shift, r, movewindow, mon:2

# Management
bind = $mod Shift, c, killactive,
bind = $mod Ctrl Shift, c, exec, hyprctl kill # Forcefully zap a window
bind = $mod Ctrl, Q, exit,
bind = $mod, t, togglefloating,
bind = $mod, f, fullscreen, 1
bind = $mod Shift, f, fullscreen, 0 # Maximize
bind = $mod $mod2, f, fullscreenstate, 0 3
bind = $mod Shift, p, pin
## Minimize -- doesnt seem to ever come back
# bind = $mod, z, togglespecialworkspace, min
# bind = $mod, z, movetoworkspace, +0
# bind = $mod, z, togglespecialworkspace, min
# bind = $mod, z, movetoworkspace, special:min
# bind = $mod, z, togglespecialworkspace, min
# bind = $mod, x, togglespecialworkspace, min2
# bind = $mod, x, movetoworkspace, +0
# bind = $mod, x, togglespecialworkspace, min2
# bind = $mod, x, movetoworkspace, special:min2
# bind = $mod, x, togglespecialworkspace, min2

# Layout
## Master
bind = $mod, Return, layoutmsg, swapwithmaster
## Dwindle
# bind = $mod Shift, x, togglegroup, none
# bind = $mod Ctrl, x, togglesplit,
# bind = $mod Ctrl Shift, x, changegroupactive, f

# Window
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d
## Move
bind = $mod Shift, h, movewindow, l
bind = $mod Shift, l, movewindow, r
bind = $mod Shift, k, movewindow, u
bind = $mod Shift, j, movewindow, d
## Resize
bind = $mod Ctrl, h, resizeactive, -50 0
bind = $mod Ctrl, l, resizeactive, 50 0
bind = $mod Ctrl, k, resizeactive, 0 -50
bind = $mod Ctrl, j, resizeactive, 0 50

# Mouse
bindm = $mod2, mouse:272, movewindow
bindm = $mod2, mouse:273, resizewindow
bind = $mod2, mouse_down, split:workspace, e+1
bind = $mod2, mouse_up, split:workspace, e-1

# Plugins


# # Toggle all keybinds
# # WARNING: (Needs to be at the bottom or keybinds under it wont work)
# bind = $mod Shift, z, submap, clean
# submap = clean
# bind = $mod Shift, z, submap, reset
# submap = reset
