-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --== Shadorain Hyprland Keybinds ==-- #

-- == Additional == #

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- == Theming == #

-- env = GTK_THEME,catppuccin-mocha-lavender-standard+default # Set a GTK theme manually, for those who want to avoid appearance tools such as lxappearance or nwg-look

-- XCURSOR_THEME                                            # Set your cursor theme. The theme needs to be installed and readable by your user.

-- XCURSOR_SIZE                                             # Set cursor size. See here for why you might want this variable set.

-- export XCURSOR_SIZE=24

-- == QT Specifications == #

-- env = QT_AUTO_SCREEN_SCALE_FACTOR,1             # (From the Qt documentation) enables automatic scaling, based on the monitor’s pixel density

-- env = QT_QPA_PLATFORM,wayland;xcb               # Tell Qt applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

-- Disables window decorations on Qt applications

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- Tells Qt based applications to pick your theme from qt5ct, use with Kvantum.

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

hl.env("SDL_IM_MODULE", "fcitx")

hl.env("GLFW_IM_MODULE", "ibus")

hl.env("INPUT_METHOD", "fcitx")

-- == XDG Specifications == #

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_CURRENT_SESSION_TYPE", "wayland")

-- == Toolkit Backend Specifications == #

hl.env("GDK_BACKEND", "wayland,x11,*")

-- GTK: Use wayland if available. If not: try x11, then any other GDK backend.

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-- Qt: Use wayland if available, fall back to x11 if not.

-- env = SDL_VIDEODRIVER,wayland,x11,windows       # Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues

hl.env("SDL_VIDEODRIVER", "wayland")

-- Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues

hl.env("CLUTTER_BACKEND", "wayland")

-- Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend

hl.env("STEAM_RUNTIME", 1)

-- Screen tearing

-- == Nvidia Specifications == #

-- env = GBM_BACKEND,nvidia-drm            # [Disable for Firefox crashing]

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

-- [Disable for screen-share failing]

hl.env("LIBVA_DRIVER_NAME", "nvidia")

-- Hardware acceleration on NVIDIA GPUs

hl.env("WLR_DRM_NO_ATOMIC", 1)

-- Screen tearing

hl.env("NVD_BACKEND", "direct")

-- VA-API hardware video acceleration

-- == Misc == #

hl.env("GTK_USE_PORTAL", 1)

hl.env("GDK_DEBUG", "portals")

hl.env("EGL_PLATFORM", "wayland")

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

hl.env("GDK_SCALE", 1)

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- Firefox wayland support

hl.env("MOZ_DISABLE_RDD_SANDBOX", 1)

hl.env("EGL_PLATFORM", "wayland")
