-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local qs = "qs -c sleex"

-- Hypr


-- Extra plugins


-- Idle listener


-- Idle prevention


-- Start all plugins


-- For fancy wallpapers


-- Quickshell

-- Input method




-- Logitech devices manager

-- Local Music




-- Forward bluetooth media commands to MPRIS

-- Clipboard history



-- Auth


-- GUI permissions helper

-- Misc




-- Misc


-- Starts neovim once on startup and closes it after 15 seconds since initial start is longer.

-- == Startup Apps == #

-- NOTE: Left: 10-18 , Middle: 0-9 , Right: 19-27

-- exec-once = [workspace 20 silent; fullscreen] notion-app




-- Post Start


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("pypr")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("vigiland")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("qs -c sleex -d")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 20")
    hl.exec_cmd("solaar -w hide")
    hl.exec_cmd("mpd")
    hl.exec_cmd("sleep 1 && mpd-mpris -port 6600")
    hl.exec_cmd("mpris-proxy")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ||/usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("safeeyes -e")
    hl.exec_cmd("accountable2you.debug")
    hl.exec_cmd("gnome-keyring-daemon --start --components=\"secrets,pkcs11,ssh\"")
    hl.exec_cmd("timeout 15s/usr/local/bin/nvim &")
    hl.exec_cmd("[workspace 10 silent; fullscreen] zen-browser")
    hl.exec_cmd("[workspace 2 silent; fullscreen] ticktick")
    hl.exec_cmd("[workspace 3 silent; fullscreen] steam")
    hl.exec_cmd("sleep 1 && qs -c sleex ipc call lock lock")
end)
