-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --== Shadorain Hyprland Window Rules ==-- #

hl.window_rule({
    name  = "opacity_0_99_0_99",
    match = {
        fullscreen = 1,
    },
    opacity = "0.99 0.99",
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(- Iced)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Press v)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(press)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Emulator)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(code)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(firefox)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(zen)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(chrome)(.*)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(chromium)(.*)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        title = "^(Ghost of Tsushima)(.*)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        class = "^(Emulator)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "opaque_on",
    match = {
        title = "^(BLACK DESERT)(.*)$",
    },
    -- TODO: review rule: "opaque on"
})

-- Flutter Apps

hl.window_rule({
    name  = "opaque_on",
    match = {
        title = "^(LyricIn)$",
    },
    -- TODO: review rule: "opaque on"
})

hl.window_rule({
    name  = "memento",
    match = {
        title = "memento",
    },
    opaque = true,
    float = true,
    move = { 2090, 65 },
    size = { 400, 869 },
    workspace = 11,
    rounding = 20, -- was 56 in the old config; 0.56.2 enforces a max of 20
})

-- Misc Apps

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(waypaper)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(blueman-manager)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "org\\.gnome\\.FileRoller",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "file-roller",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(CachyOSHello)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^()$",
        title = "^(Steam- Self Updater)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "animation_popin",
    match = {
        title = "^(SafeEyes.*)$",
    },
    -- TODO: review rule: "animation popin"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "org\\.quickshell",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "fullscreen_state_0_3",
    match = {
        class = "^(chrome-app)$",
    },
    -- TODO: review rule: "fullscreen_state 0 3"
})

hl.window_rule({
    name  = "tile_on",
    match = {
        class = "^(chrome-app)$",
    },
    -- TODO: review rule: "tile on"
})

-- Tearing

hl.window_rule({
    name  = "immediate_on",
    match = {
        title = ".*\\.exe",
    },
    -- TODO: review rule: "immediate on"
})

hl.window_rule({
    name  = "immediate_on",
    match = {
        title = ".*minecraft.*",
    },
    -- TODO: review rule: "immediate on"
})

hl.window_rule({
    name  = "immediate_on",
    match = {
        class = "^(steam_app).*",
    },
    -- TODO: review rule: "immediate on"
})

-- == Screensharing == #

hl.window_rule({
    name  = "Wayland Video Bridge",
    match = {
        class = "xwaylandvideobridge",
    },
    opacity = 0.0,
    no_anim = true,
    no_initial_focus = true,
    no_blur = true,
    max_size = { 1, 1 },
})

-- == Scratchpad == #

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "ncmpcpp",
    },
    -- TODO: review rule: "float on"
})

hl.layer_rule({
    match = {
        namespace = "match:class kitty",
    },
    animation = "slide top",
})

-- == Dialogs == #

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Open File)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Select a File)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Open Folder)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Save As)(.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Library)(.*)$",
    },
    -- TODO: review rule: "float on"
})

--# XWayland Popups

hl.window_rule({
    name  = "no_dim_on",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    -- TODO: review rule: "no_dim on"
})

hl.window_rule({
    name  = "no_shadow_on",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    -- TODO: review rule: "no_shadow on"
})

hl.window_rule({
    name  = "rounding_10",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    rounding = 10,
})

-- Picture in picture (resize and move done via script)

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "keep_aspect_ratio_on",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*",
    },
    -- TODO: review rule: "keep_aspect_ratio on"
})

hl.window_rule({
    name  = "move_73__72_",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*",
    },
    move = "73% 72%",
})

hl.window_rule({
    name  = "size_25__0_",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*",
    },
    size = "25% 0%",
})

hl.window_rule({
    name  = "pin_on",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*",
    },
    -- TODO: review rule: "pin on"
})

-- Steam

hl.window_rule({
    name  = "rounding_10",
    match = {
        class = "steam",
    },
    rounding = 10,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "Friends List",
        class = "steam",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "immediate_on",
    match = {
        class = "steam_app_[0-9]+",
    },
    -- TODO: review rule: "immediate on"
})

-- Allow tearing for steam games

hl.window_rule({
    name  = "idle_inhibit_always",
    match = {
        class = "steam_app_[0-9]+",
    },
    -- TODO: review rule: "idle_inhibit always"
})

-- Always idle inhibit when playing a steam game

-- == Custom Apps == #

--# -- Dioxus -- ##

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(.*dioxus.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "monitor_dp-4",
    match = {
        title = "^(.*dioxus.*)$",
    },
    monitor = "DP-4",
})

hl.window_rule({
    name  = "no_initial_focus_on",
    match = {
        title = "^(.*dioxus.*)$",
    },
    -- TODO: review rule: "no_initial_focus on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(.*Multimedia Compression.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "monitor_dp-4",
    match = {
        title = "^(.*Multimedia Compression.*)$",
    },
    monitor = "DP-4",
})

hl.window_rule({
    name  = "workspace_2_silent",
    match = {
        title = "^(.*Multimedia Compression.*)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    name  = "no_initial_focus_on",
    match = {
        title = "^(.*Multimedia Compression.*)$",
    },
    -- TODO: review rule: "no_initial_focus on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Shadocal.*)$",
    },
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "monitor_dp-4",
    match = {
        title = "^(Shadocal.*)$",
    },
    monitor = "DP-4",
})

hl.window_rule({
    name  = "no_initial_focus_on",
    match = {
        title = "^(Shadocal.*)$",
    },
    -- TODO: review rule: "no_initial_focus on"
})

-- == Layers == #

--# Layer rules

hl.layer_rule({
    match = {
        namespace = "hyprpicker",
    },
    animation = "fade",
})

-- Colour picker out animation

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    animation = "fade",
})

-- wlogout

hl.layer_rule({
    match = {
        namespace = "selection",
    },
    animation = "fade",
})

-- slurp

hl.layer_rule({
    match = {
        namespace = "wayfreeze",
    },
    animation = "fade",
})

-- Launcher & Notifications

hl.layer_rule({
    blur = true,
    animation = "popin 80%",
    ignore_alpha = 0.5,
})

hl.layer_rule({
    blur = true,
    ignore_alpha = 0.69,
})

-- Shell

hl.layer_rule({
    match = {
        namespace = "quickshell:.*",
    },
    blur_popups = true,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:.*",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:.*",
    },
    ignore_alpha = 0.79,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:bar",
    },
    animation = "slide",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:screenCorners",
    },
    animation = "fade",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:sidebarRight",
    },
    animation = "slide right",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:sidebarLeft",
    },
    animation = "slide left",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:osk",
    },
    animation = "slide bottom",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:dock",
    },
    animation = "slide bottom",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:dashboard",
    },
    animation = "slide bottom",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:mediaControls",
    },
    animation = "slide top",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:session",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:session",
    },
    animation = "slide top",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:session",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:notificationPopup",
    },
    animation = "fade",
})

hl.layer_rule({
    match = {
        namespace = "quickshell:backgroundWidgets",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:backgroundWidgets",
    },
    ignore_alpha = 0.05,
})

hl.layer_rule({
    match = {
        namespace = "quickshell:lockScreen",
    },
    animation = "slide top",
})

hl.layer_rule({
    match = {
        namespace = "shell:bar",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "shell:notifications",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "shell:notifications",
    },
    ignore_alpha = 0.1,
})
