add_newline = false

format = """
 $directory\
$git_branch\
$git_status\
$character
"""
# $line_break\

[character]
format = " $symbol "
success_symbol = "[❱](cyan)"
error_symbol = "[❱](red)"
vicmd_symbol = "[❮](blue)"

[directory]
format = "[ ](magenta) [$path]($style)($read_only_style) "
style = "blue"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"
disabled = false

[git_status]
format = '[$deleted $renamed $modified $staged $untracked $ahead]($style)'
ahead = "[${count}](yellow)"
untracked = "[?${count}](bold)"
modified = "[!${count}](bold)"
staged = "[+${count}](bold green)"
deleted = "[✘${count}](bold red)"
renamed = "[»${count}](bold magenta)"
style = "bold blue"
