-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --== Shadorain Hyprland Config ==-- #

require("config.env")
require("config.start")
require("config.binds")
require("config.windowrules")
require("config.animations")
require("monitors")

hl.config({
	input = {
		kb_layout = "us",
		kb_options = "caps:escape",
		repeat_delay = 250,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
			disable_while_typing = true,
			scroll_factor = 3,
		},
	},

	gestures = {
		workspace_swipe_touch = true,
		workspace_swipe_min_speed_to_force = 4,
	},

	group = {
		groupbar = {
			font_family = "JetBrains Mono NF",
			font_size = 15,
			gradients = true,
			gradient_round_only_edges = false,
			gradient_rounding = 5,
			height = 25,
			indicator_height = 0,
			gaps_in = 3,
			gaps_out = 3,
		},
		col = {
			border_active = "0xAAbd93f9",
			border_inactive = "0xAA35355E",
		},
	},

	dwindle = {
		force_split = 2,
		preserve_split = true,
		use_active_for_splits = true,
	},

	master = {
		special_scale_factor = 0.8,
		new_status = "slave",
		new_on_top = false,
	},

	general = {
		layout = "dwindle",
		-- main_mod = ALT
		gaps_in = 8,
		gaps_out = 8,
		border_size = 2,
		allow_tearing = false,
		col = {
			active_border = "0xAAbd93f9",
			inactive_border = "0xAA35355E",
		},
	},

	cursor = {
		no_hardware_cursors = true,
	},

	render = {
		-- explicit_sync = 2
		-- explicit_sync_kms = 2
	},

	decoration = {
		rounding = 10,
		active_opacity = 1,
		inactive_opacity = 0.8,
		fullscreen_opacity = 0.9,
		blur = {
			size = 2,
			passes = 6,
			noise = 0.10,
			popups = true,
			input_methods = true,
		},
		shadow = {
			enabled = true,
			range = 10,
			render_power = 3,
			-- ignore_window = true
			color = "0x33000000",
			-- color = 0x990F0F0F
			color_inactive = "0x22000000",
		},
	},

	misc = {
		vrr = 2,
		font_family = "JetBrains Mono NF",
		animate_manual_resizes = true,
		animate_mouse_windowdragging = true,
		disable_hyprland_logo = true,
		force_default_wallpaper = 0,
		on_focus_under_fullscreen = 2,
		allow_session_lock_restore = true,
		session_lock_xray = true,
		middle_click_paste = false,
		focus_on_activate = true,
		-- mouse_move_enables_dpms = true
		-- key_press_enables_dpms = true
	},

	ecosystem = {
		no_donation_nag = true,
	},

	debug = {
		error_position = 1,
	},
})

-- == Plugins == #

-- hyprexpo is not currently installed via hyprpm (only hyprland-plugins repo
-- with borders-plus-plus/csgo-vulkan-fix/hyprbars/hyprfocus is enabled).
-- Re-enable via `hl.plugin("hyprexpo", ...)` (see plugin's own lua docs)
-- once reinstalled. Old settings for reference:
--   columns = 3, gap_size = 5, bg_col = "rgb(111111)",
--   workspace_method = "center current"

-- hyprsplit: C++ plugin is dead upstream, replaced by this Lua library.
require("hyprsplit").config({ num_workspaces = 9 }) -- Left: 10-18, Middle: 19-27, Right: 0-9
