-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2025-08-02 at 18:05:04. Do not edit manually.

hl.monitor({
    output   = "DP-2",
    mode     = "2560x1440@59.95",
    position = "5120x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-3",
    mode     = "2560x1440@59.95",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-4",
    mode     = "2560x1440@143.97",
    position = "2560x0",
    scale    = 1.0,
})
